### GET ALL ORDERS
GET http://localhost:8080/saved4_war_exploded/api/orders

### GET FILTERED ORDERS  (SHARED)
GET http://localhost:8080/saved4_war_exploded/api/orders?is_shared=true

### GET FILTERED ORDERS  (REQUESTER & CONTAINER)
GET http://localhost:8080/saved4_war_exploded/api/orders?requester=admin_1&container_id=1

### GET FILTERED ORDERS  (ONE STATUS)
GET http://localhost:8080/saved4_war_exploded/api/orders?status=created

### GET FILTERED ORDERS  (ONE ROUTE ID)
GET http://localhost:8080/saved4_war_exploded/api/orders?order_for=company_a


### GET FILTERED ORDERS  (MULTIPLE STATUS)
GET http://localhost:8080/saved4_war_exploded/api/orders?status=created&status=completed&
    status=undergoing

### GET FILTERED ORDERS  (VEHICLE)
GET http://localhost:8080/saved4_war_exploded/api/orders?route_id=1


### GET ONE ORDER
GET http://localhost:8080/saved4_war_exploded/api/orders/

### PATH SPECIFIC ORDER
PATCH http://localhost:8080/saved4_war_exploded/api/orders/7
Content-Type: application/json

{
  "orderId": 1,
  "containerId": 1,
  "vehicleId": 3,
  "requester": "user_test123",
  "routeId": 1,
  "madeAt": "2025-06-17T22:00:00.000+00:00",
  "source": "port",
  "destination": "user_test123",
  "twStart": "2025-06-19T08:00:00.000+00:00",
  "twEnd": "2025-06-19T10:00:00.000+00:00",
  "eta": null,
  "status": "created",
  "operationType": "loading",
  "freightValue": 10313.79,
  "sourcePosition": {
    "x": 4.4777,
    "y": 51.9244
  },
  "destinationPosition": {
    "x": 4.500123,
    "y": 51.923456
  },
  "freightWeight": 1000.00,
  "freightType": "food",
  "shared": true
}

### PATCH WITH ONE ITEM
PATCH http://localhost:8080/saved4_war_exploded/api/orders/53
Content-Type: application/json

{
  "order_for":"company_b",
  "source": "company_b",
  "destination": "rotterdam_port"
}
### PATCH with shared
PATCH http://localhost:8080/saved4_war_exploded/api/orders/81
Content-Type: application/json

{
  "shared": true
}
### PATCH WITH ONE ITEM
PATCH http://localhost:8080/saved4_war_exploded/api/orders/69
Content-Type: application/json

{
  "status": "scheduled",
  "vehicleId" : 2
}

### ADD ORDER
POST http://localhost:8080/saved4_war_exploded/api/orders
Content-Type: application/json

{
  "destination": "company_b",
  "freightType": null,
  "freightValue": "",
  "freightWeight": "",
  "madeAt": "2025-06-18T22:28:13+02:00",
  "operationType": "unloading",
  "shared": false,
  "source": "company_a",
  "status": "completed",
  "twEnd": "2025-06-18T22:43:00+02:00",
  "twStart": "2025-06-18T22:28:00+02:00",
  "requester": "company_b"
}


### DELETE ORDER
DELETE http://localhost:8080/saved4_war_exploded/api/orders/15


### GET ORDER FROM SPECIFIC COMPANY
GET http://localhost:8080/saved4_war_exploded/api/orders/by-username/user_test123
Content-Type: application/json


### GET ALL COMPANIES LIST
GET http://localhost:8080/saved4_war_exploded/api/orders/company-list
Content-Type: application/json


### GET ALL COMPANIES LIST
GET http://localhost:8080/saved4_war_exploded/api/orders/company-list
Content-Type: application/json
